Fix the formatting lint check

diff --git a/toast.yml b/toast.yml
--- a/toast.yml
+++ b/toast.yml
@@ -107,7 +107,10 @@ tasks:
         --deny warnings --deny clippy::all --deny clippy::pedantic
 
       # Check code formatting.
-      cargo fmt --all -- --check || echo 'ERROR: Please correct the formatting errors above.' 1>&2
+      if ! cargo fmt --all -- --check; then
+        echo 'ERROR: Please correct the formatting errors above.' 1>&2
+        exit 1
+      fi
 
       # Check references.
       tagref
